### ISSUE TITLE
Spellbook crashes clients

### ISSUE THREAD

**Issue by djoveryde** [djoveryde/Hexx-Reloaded#1]
Using an AM2 Spellbook wether it be obtained from a chest or crafted causes players to get immediately booted with "An Internal Error has Occurred". 

Oddly I cannot recreate it personally even if I am handed the players spellbook.

If anyone else can give any details about this please do!

**Comment by djoveryde** [comment]
Edit: Arcane Spellbook causes myself to crash once the Soulbound element is removed. For another players having soulbound crashes them. Really odd??

**Comment by djoveryde** [comment]
Issue relates potentially to a discrepancy between client and server enchantment IDS. Would need adding as is currently missing it's ID section.

enchantments {
I:magic_resist=100
I:soulbound=101
}

**Comment by NicPlayZ** [comment]
For me it doesnt happen with the arcane spellbook but it happens with the normal one I don't know why...

**Comment by djoveryde** [comment]
Found huge chunk missing serverside for multiple abilities which is interesting, could have been a gen issue with an older version of the mod perhaps. Corrected this. Client and server now match.
Further testing

**Comment by djoveryde** [comment]
Still exists but error serverside was recorded, doesnt help much though 

23.03 11:32:56 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_71] 
23.03 11:32:56 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?] 
23.03 11:32:56 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:946) ~[nh.class:?] 
23.03 11:32:56 [Server] INFO java.lang.NullPointerException 
23.03 11:32:56 [Server] WARN Failed to handle packet for /58.182.96.45:50394

**Comment by djoveryde** [comment]
Issue may actually be Optifine. Which is needed for 32 bit players to use the modpack. This is being tested.

Update: Issue can be duplicated by looking at a block when opening the spellbook. If not optifine this could be WAILA

23-03-2015 - 14:11 - Nope, singleplayer works fine. but MP crashes, even with WAILA, Optifine and inventory tweaks disabled.

23-03-2015 - 15:01 - Tried with a generic Forge Server. Works fine. Issue may be Cauldron which cannot be fixed if so.

**Comment by djoveryde** [comment]
End result, players should not look at a block while opening spellbooks

**Comment by djoveryde** [comment]
Issue resolved in later cauldron update
