### ISSUE TITLE
Can start Modpack, but with the framerate of a potato   (32 bit)

### ISSUE THREAD

**Issue by MightyTidy** [djoveryde/Hexx-Reloaded#13]
On multiplayer it is better noticeably but i would also like to play single player.

(i have a great graphics card, just a 32 bit) i have all of my settings on the lowest possible any help?

maybe install fastcraft on the pack?

**Comment by djoveryde** [comment]
If your using the 32 but version of the modpack already you can try updating  optifine to hd standard version 5 which for some has fixed multiple issues. Fast craft actually makes the pack unplayable (ram is used up).
Let me know if the optifine update fixes it for you :)
