### ISSUE TITLE
textures

### ISSUE THREAD

**Issue by jsalerno11** [djoveryde/Hexx-Reloaded#2]
i installed the texture pack and now the game keeps crashing before the main screen.  Is this common?

**Comment by djoveryde** [comment]
How much ram have you got allocated to technic, which windows version do you have (x64 or x32).

Adam Drury (Senior Workshop Engineer, West Wiltshire Micros)

**Comment by jsalerno11** [comment]
Windows 8.1, x64, and 4.41 mb.

James E. Salerno

**Comment by djoveryde** [comment]
I'll be doing a 64x version soon, give that a go once it's released and let me know if it's all good :)

**Comment by jsalerno11** [comment]
Thanks but, what should i do about my game now

James E. Salerno

**Comment by djoveryde** [comment]
Click the smaller cog in the right of the  modpack, open it to get to its folder and remove the file from texture packs folder, it will revert it to generic state

**Comment by jsalerno11** [comment]
ah thank you so much. : )

James E. Salerno
