### ISSUE TITLE
Unable to move after logging in... when i try to type something it says cannot send chat messeges.. i dont know.

### ISSUE THREAD

**Issue by DevilHerobrine** [djoveryde/Hexx-Reloaded#3]
this is very odd... i cant move... cant right click, and no one can hear me...

**Comment by DevilHerobrine** [comment]
fixed after restart

**Comment by djoveryde** [comment]
All working now? It's usually a corrupt chunk that causes that but guess it just needed unloading.

**Comment by djoveryde** [comment]
Issue will be closed. I will look into a world chunk checker to see if there are any issues with chunks
