### ISSUE TITLE
Thaumcraft Research Glitch

### ISSUE THREAD

**Issue by NicPlayZ** [djoveryde/Hexx-Reloaded#4]
So even though I said the problem was when clicking on research or crafting in the crucible, I have realized it is not the problem. The main problem is that everytime I try to craft a knowledge tome, it glitches and dissapears. After that the next thing I do with thaumcraft I get a fatal error from the server and get kicked. When I rejoin all of my items drop onto the floor before I get kicked so if im the only person loading the chunk, I lose my items. It might be with a custom mod for thaumcraft thats on my client which shows names of aspects when I hover over them. The items that I want refunded now are:

Fully charged silverwood thaumium wand to craft my real wand.
2 Ichor wand caps
1 primal staff core
1 thaumometer
1 Awakened ichorium pickaxe.
almost a stack of mixed crystal clusters
1 Ichorcloth cowl of the abyssal depths.
1 Ichorcloth leggings of the burning mantle.
3 Node stabilizers I wanted to set up
3 Aura nodes I was going to set up.
All of my research which was everything except the special ichorcloth chestplate and boots.

**Comment by djoveryde** [comment]
Issue is related to Thuamic Tinkerer. 
Could be due to the serverside having the following:

```
# Set to false to disable the crafting recipe for the Tome of Research Sharing.
B:shareTome.survival.enabled=false
```

Sent issue over to the ThaumTink Owner for investigation.
