### ISSUE TITLE
Thaumcraft Spawn Issue

### ISSUE THREAD

**Issue by Glossyflame** [djoveryde/Hexx-Reloaded#5]
When I went to spawn I miss clicked on a thaumcraft wand with the foci:Equal Trade and it replaced the blocks in spawn on accident so this could probely result in destroying the beautiful spawn that the mods an up made

**Comment by Glossyflame** [comment]
Or it could bypass factions claims by stealing possibly valuable nlocks

**Comment by Glossyflame** [comment]
Blocks*

**Comment by djoveryde** [comment]
Its been banned, only because it has no ability to control it within protected regions

**Comment by djoveryde** [comment]
thankyou for the report

**Comment by Glossyflame** [comment]
Your welcome
