### ISSUE TITLE
TerraSteel issue

### ISSUE THREAD

**Issue by Glossyflame** [djoveryde/Hexx-Reloaded#7]
From what I've been doing in botanist I noticed that when I make terra steel it keeps disapering when it's about to finish so all I'm asking for is to extend the deadline for all items disappearing please

**Comment by djoveryde** [comment]
What server is this for? I'm guessing it
Would be towny as that's still got an active Clearlagg from previous owner

**Comment by Glossyflame** [comment]
I'm its for factions

**Comment by Glossyflame** [comment]
Um*

**Comment by djoveryde** [comment]
Factions has a manual clear lag meaning there's no auto removal, unless it's on the floor for 10 minutes it shouldn't de spawn unless one of the staff ran a manual cleanup

**Comment by Glossyflame** [comment]
Okay
